# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuG5jbec723aUsxaqcE3Sp3y-rpcO9eE

Hyperliquid Trader Performance vs Fear & Greed Index Analysis

Load
"""

import pandas as pd

fg = pd.read_csv('/content/fear_greed_index.csv')
hist = pd.read_csv('/content/historical_data.csv')
print(fg.shape, hist.shape)

"""Parse dates"""

fg['date'] = pd.to_datetime(fg['date'])
hist['Timestamp IST'] = pd.to_datetime(hist['Timestamp IST'], format='%d-%m-%Y %H:%M')
hist['date'] = hist['Timestamp IST'].dt.normalize()

"""Merge sentiment onto trades"""

merged = hist.merge(fg[['date', 'classification', 'value']], on='date', how='left')
print(merged['classification'].isna().sum(), "unmatched trades")
merged = merged.dropna(subset=['classification'])
print(merged.shape)

"""Isolate closing trades"""

closes = merged[merged['Closed PnL'] != 0].copy()
closes['win'] = closes['Closed PnL'] > 0

"""Core finding: sentiment vs performance"""

order = ['Extreme Fear','Fear','Neutral','Greed','Extreme Greed']

summary = closes.groupby('classification').agg(
    trades=('win', 'size'),
    win_rate=('win', 'mean'),
    avg_pnl=('Closed PnL', 'mean'),
    total_pnl=('Closed PnL', 'sum')
).reindex(order)
summary['win_rate'] = (summary['win_rate'] * 100).round(2)
print(summary)

"""Long/short bias by sentiment"""

opens = merged[merged['Direction'].isin(['Open Long', 'Open Short'])]
bias = opens.groupby(['classification', 'Direction'])['Size USD'].sum().unstack().reindex(order)
bias['long_pct'] = (bias['Open Long'] / (bias['Open Long'] + bias['Open Short']) * 100).round(1)
print(bias)

""" Differentiator #1: per-account consistency"""

account_perf = closes.groupby(['Account', 'classification'])['Closed PnL'].sum().unstack().reindex(columns=order)
account_perf['consistency_std'] = account_perf.std(axis=1)
account_perf['total_pnl'] = account_perf[order].sum(axis=1)

print("Most sentiment-sensitive accounts (high swing between regimes):")
print(account_perf.sort_values('consistency_std', ascending=False).head(5)[['total_pnl','consistency_std']])

print("\nMost sentiment-agnostic accounts (stable across regimes):")
print(account_perf.sort_values('consistency_std').head(5)[['total_pnl','consistency_std']])

profitable = (account_perf['total_pnl'] > 0).sum()
total_accounts = len(account_perf)

print(f"{profitable} of {total_accounts} accounts are profitable overall.")

"""Charts

"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(16,4))
colors = ['#8B0000','#E4572E','#999999','#5B9A54','#1B5E20']

summary['win_rate'].plot(kind='bar', ax=axes[0], color=colors, title='Win Rate (%)')
summary['avg_pnl'].plot(kind='bar', ax=axes[1], color=colors, title='Avg PnL/Trade ($)')
bias['long_pct'].plot(kind='bar', ax=axes[2], color=colors, title='Long Position Share (%)')

for ax in axes:
    ax.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.show()

"""Summary: I merged more than 211,000 Hyperliquid trades with the daily Fear & Greed Index to analyze whether market sentiment is related to trader performance. The analysis shows that traders achieved the highest win rate and average profit during Fear, while the lowest performance occurred during Greed, indicating that the relationship between sentiment and trading success is not a simple progression from fear to greed. Traders in this dataset also opened more long positions during Fear (76.2%) than during Greed (70.6%), suggesting a contrarian trading style rather than a momentum-based approach. Segmenting by account shows 20 of 22 accounts are consistently profitable overall, while a smaller group experiences significant performance swings depending on market sentiment. This suggests that market sentiment is not a universal trading edge but has a greater impact on some traders than others. A practical strategy takeaway is to increase position sizes during Fear and reduce exposure during Greed."""